// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-n7SA3CshRdmfbIAVgzDfhMqeMBK1lJI',
    appId: '1:341134101483:web:80e859d19918b6ee64a7ae',
    messagingSenderId: '341134101483',
    projectId: 'elara-adee6',
    authDomain: 'elara-adee6.firebaseapp.com',
    storageBucket: 'elara-adee6.appspot.com',
    measurementId: 'G-B14V5XH3MK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkCz4EDYkbV14Ml9oR-9LNwHkSlxgYYcM',
    appId: '1:341134101483:android:fa1a9e061982336a64a7ae',
    messagingSenderId: '341134101483',
    projectId: 'elara-adee6',
    storageBucket: 'elara-adee6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuJdYfIP6cwxlzmr9Ni4K-CoGxqG_tGKs',
    appId: '1:341134101483:ios:35b152334fafc72d64a7ae',
    messagingSenderId: '341134101483',
    projectId: 'elara-adee6',
    storageBucket: 'elara-adee6.appspot.com',
    iosClientId: '341134101483-cb8rnj7fqtoergol528h4vjobrd5a30t.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuJdYfIP6cwxlzmr9Ni4K-CoGxqG_tGKs',
    appId: '1:341134101483:ios:35b152334fafc72d64a7ae',
    messagingSenderId: '341134101483',
    projectId: 'elara-adee6',
    storageBucket: 'elara-adee6.appspot.com',
    iosClientId: '341134101483-cb8rnj7fqtoergol528h4vjobrd5a30t.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-n7SA3CshRdmfbIAVgzDfhMqeMBK1lJI',
    appId: '1:341134101483:web:2bc0ac137138012364a7ae',
    messagingSenderId: '341134101483',
    projectId: 'elara-adee6',
    authDomain: 'elara-adee6.firebaseapp.com',
    storageBucket: 'elara-adee6.appspot.com',
    measurementId: 'G-TMFDSNHM7K',
  );
}
